### ISSUE TITLE
Encoding of the config files seems to be wrong

### ISSUE THREAD

**Issue by realEthanZou** [ich777/docker-accompetizione#1]
Here are the output of ```file *``` of the configs in this repo:
```
configuration.json: data
event.json:         data
eventRules.json:    data
settings.json:      Little-endian UTF-16 Unicode text
```
Attempting to view the file with ```nano``` shows random characters.

Encoding of configs from your other repos seems to be correct. For example, the minecraft bedrock server:
```
permissions.json:  JSON data
server.properties: ASCII text
```

**Comment by ich777** [comment]
@realEthanZou thank you for the report. Does the server work in the default configuration?

The config files were taken after the game has created them and it is maybe possible that the format is different.
Can you open the files with another application?

**Comment by realEthanZou** [comment]
Thanks for the swift reply. The server can run with the default config but I cannot edit them (I tried ```nano``` and ```vi```). Maybe the game generated the configs based on the locale on your system that is not UTF-8?

I only run a couple of instances so I can manually copy the config contents to each file and edit them. No problem. But if it's indeed an encoding issue, I'd appreciate it if you can include UTF-8 encoding versions of the files instead.

**Comment by ich777** [comment]
> Maybe the game generated the configs based on the locale on your system that is not UTF-8?

I don't think so because I've created this container as usual on Unraid and it uses UTF-8.



> But if it's indeed an encoding issue, I'd appreciate it if you can include UTF-8 encoding versions of the files instead.

Can you confirm that it works with UTF-8 files too?
I personally don't own the game because I've made this container on request and can't test it, I really only want to change it if it is working for sure.

**Comment by realEthanZou** [comment]
I took a look at the acc-wiki and the default configs are indeed in UTF16-LE format. Although files in UTF-8 format work, I guess it's better to leave it as is since the typical use case of this repo is Unraid container and it works for them. Sorry I didn't look it up in the first place. Closing.
