### ISSUE TITLE
Unimplemented function

### ISSUE THREAD

**Issue by icebob** [ich777/docker-accompetizione#2]
Hello, 

great project.

However I try to execute it but I always got the following error:

```
Attaching to acc-server_acc_1
acc_1  | ---Checking if UID: 99 matches user---
acc_1  | usermod: no changes
acc_1  | ---Checking if GID: 100 matches user---
acc_1  | usermod: no changes
acc_1  | ---Setting umask to 000---
acc_1  | ---Checking for optional scripts---
acc_1  | ---No optional script found, continuing---
acc_1  | ---Starting...---
acc_1  | ---Checking if 'accServer.exe' is present---
acc_1  | ---'accServer.exe' found, continuing...---
acc_1  | ---Prepare Server---
acc_1  | ---Checking if config files are present---
acc_1  | ---Checking if WINE workdirectory is present---
acc_1  | ---WINE workdirectory found---
acc_1  | ---Checking if WINE is properly installed---
acc_1  | ---WINE properly set up---
acc_1  | ---Server ready---
acc_1  | ---Start Server---
acc_1  | 003c:err:service:RPC_Init RpcServerListen failed with error 1721
acc_1  | 002c:err:wineboot:start_services_process Unexpected termination of services.exe - exit code 1721
acc_1  | wine: Call from 0000000174013C0E to unimplemented function msvcp140.dll.?_Throw_C_error@std@@YAXH@Z, aborting
acc_1  | wine: Unimplemented function msvcp140.dll.?_Throw_C_error@std@@YAXH@Z called at address 0000000174013C0E (thread 0024), starting debugger...
acc_1  | 0048:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
acc_1  | 0048:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
acc_1  | 0048:err:systray:initialize_systray Could not create tray window
acc_1  | Can't attach process 0020: error 8
acc-server_acc_1 exited with code 0
```

Do you have any idea what the problem is?

Thanks in advance!

Icebob

**Comment by ich777** [comment]
> Do you have any idea what the problem is?

Seems like the master server is not able to reach your server.
Please check your port forwarding, please be sure to not translate the ports to other ports.

If that won't solve the issue I will look into it, please let me know if that solves the issue.

**Comment by icebob** [comment]
Thanks for the quick response. I've opened the ports but same error messages

**Comment by ich777** [comment]
Sorry for the late response, I can't reproduce this over here and the container is running just fine:
![grafik](https://github.com/ich777/docker-accompetizione/assets/28066518/0e29bc3a-03b7-487b-a691-d4218cc20a1a)

From what I can see you are not running the container on Unraid correct?
Are you sure that all environmental variables are all set correctly on your system, especially the `UID` and `GID` since these two values should exist on your system and the Docker user must be able to read/create/change files with that UID and GID.

On what system are you running the container? Is Docker and your system in general up to date?

**Comment by icebob** [comment]
@ich777 thank you for the help.

I'm trying to start the ACC server on a Contabo VM, with Ubuntu 20.04.3.
I created that compose file to set envs, here is my compose:

```yaml
icebob@vmi321719:~/acc-server$ cat docker-compose.yml
version: '3'

services:
  acc:
    image: ich777/accompetizione-server
    ports:
    - "9201:9201/tcp"
    - "9201:9201/udp"
    environment:
    - "UID=99"
    - "GID=100"
    -  "UMASK=000"
    - "DATA_PERM=770"
    volumes:
    - "./files:/acc"
```

Here is the content of files folder

```
root@vmi321719:/home/icebob/acc-server/files# ls -al
total 44952
drwxrwx--- 11     99 users      4096 May  5 15:03 .
drwxrwxr-x  3 icebob icebob     4096 May  5 15:00 ..
-rwxrwx---  1     99 users   1775616 May  1 12:18 accServer.exe
drwxrwx---  3     99 users      4096 May  5 15:02 .cache
drwxrwx---  3     99 users      4096 May  5 15:03 cfg
-rwxrwx---  1     99 users      3798 May  1 12:18 changelog.txt
drwxrwx---  3     99 users      4096 May  5 15:03 .config
drwxrwx---  3     99 users      4096 May  5 15:03 .local
drwxrwx---  2     99 users      4096 May  5 15:03 log
drwxrwx---  2     99 users      4096 May  5 15:03 results
drwxrwx---  3     99 users      4096 May  5 14:47 sdk
drwxrwx---  3     99 users      4096 May  5 14:47 server
-rwxrwx---  1     99 users  22808784 May  1 12:18 steamclient64.dll
-rwxrwx---  1     99 users  19381096 May  1 12:18 steamclient.dll
-rwxrwx---  1     99 users    403816 May  1 12:18 tier0_s64.dll
-rwxrwx---  1     99 users    349544 May  1 12:18 tier0_s.dll
-rwxrwx---  1     99 users    707944 May  1 12:18 vstdlib_s64.dll
-rwxrwx---  1     99 users    543592 May  1 12:18 vstdlib_s.dll
drwxrwx---  4     99 users      4096 May  5 15:02 WINE64
```

I think the user (99) is not exist on the host. Can I change the UID=99 to an existing user UID, or it should be 99?

**Comment by ich777** [comment]
> I think the user (99) is not exist on the host. Can I change the UID=99 to an existing user UID, or it should be 99?

You have to change it to a UID and GID that actually exists on your system and Docker itself is able to use, most of the times on Ubuntu it's `1000`

Please also make sure that Docker is up to date, what Docker version are you running?

**Comment by icebob** [comment]
Thanks, I changed it to 1000 and changed the owners on the files, but I've got the same error

```
acc_1  | ---Checking if UID: 1000 matches user---
acc_1  | usermod: no changes
acc_1  | ---Checking if GID: 1000 matches user---
acc_1  | usermod: no changes
acc_1  | ---Setting umask to 000---
acc_1  | ---Checking for optional scripts---
acc_1  | ---No optional script found, continuing---
acc_1  | ---Starting...---
acc_1  | ---Checking if 'accServer.exe' is present---
acc_1  | ---'accServer.exe' found, continuing...---
acc_1  | ---Prepare Server---
acc_1  | ---Checking if config files are present---
acc_1  | ---Checking if WINE workdirectory is present---
acc_1  | ---WINE workdirectory found---
acc_1  | ---Checking if WINE is properly installed---
acc_1  | ---WINE properly set up---
acc_1  | ---Server ready---
acc_1  | ---Start Server---
acc_1  | 003c:err:service:RPC_Init RpcServerListen failed with error 1721
acc_1  | 002c:err:wineboot:start_services_process Unexpected termination of services.exe - exit code 1721
acc_1  | wine: Call from 0000000174013C0E to unimplemented function msvcp140.dll.?_Throw_C_error@std@@YAXH@Z, aborting
acc_1  | wine: Unimplemented function msvcp140.dll.?_Throw_C_error@std@@YAXH@Z called at address 0000000174013C0E (thread 0024), starting debugger...
acc_1  | 0048:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
acc_1  | 0048:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
acc_1  | 0048:err:systray:initialize_systray Could not create tray window
acc_1  | Can't attach process 0020: error 8
acc-server_acc_1 exited with code 0
```

Could you show your file and directory structure of ACC server?

**Comment by ich777** [comment]
> Thanks, I changed it to 1000 and changed the owners on the files, but I've got the same error

Can you please answer my question if your Docker version is also up to date?
You can get the version by issuing: `docker --version` on the host machine.


> Could you show your file and directory structure of ACC server?

Sure:
![grafik](https://github.com/ich777/docker-accompetizione/assets/28066518/abbaecb5-857a-4238-abee-471599c0db3f)


BTW, I have now confirmation from three other users that the container is working fine on their Unraid machines.

**Comment by icebob** [comment]
Thanks for the confirmation, it means my server env is different. I've checked the docker version, it's not the latest, its `20.10.8`
I will try to upgrade it.

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Are there any special on Unraid machines compared to a simple VM?

**Comment by ich777** [comment]
> I will try to upgrade it.

I think the underlying issue is that your Docker version is way out of date, Docker latest version is `25` IIRC.
This is a Docker build from 2021, you should definitely upgrade!



> Are there any special on Unraid machines compared to a simple VM?

No.

**Comment by icebob** [comment]
I've upgraded to 26.1.1 and it works, thanks!

Sorry for bothering you with the issue. Thanks again!
